"""Initial schema with all tables

Revision ID: 457f09125f49
Revises: 
Create Date: 2025-11-14 12:09:13.675217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = '457f09125f49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('incident_id', sa.String(length=255), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_created_at'), 'agent_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_sessions_incident_id'), 'agent_sessions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_entity', 'attachments', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_attachments_entity_id'), 'attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachments_entity_type'), 'attachments', ['entity_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('diff_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_created_user', 'audit_logs', ['created_at', 'user_id'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity_level'), nullable=False),
    sa.Column('workflow_state', sa.Enum('DRAFT', 'IN_REVIEW', 'PUBLISHED', 'RETIRED', 'MERGED', name='workflow_state'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='entry_status'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('impact_summary', sa.Text(), nullable=True),
    sa.Column('detection_method', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['merged_into_id'], ['entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entries_created_at', 'entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_entries_merged_into_id'), 'entries', ['merged_into_id'], unique=False)
    op.create_index(op.f('ix_entries_severity'), 'entries', ['severity'], unique=False)
    op.create_index(op.f('ix_entries_status'), 'entries', ['status'], unique=False)
    op.create_index(op.f('ix_entries_title'), 'entries', ['title'], unique=False)
    op.create_index('ix_entries_workflow_severity', 'entries', ['workflow_state', 'severity'], unique=False)
    op.create_index(op.f('ix_entries_workflow_state'), 'entries', ['workflow_state'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt_template', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ab_test_group', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompts_active', 'prompts', ['is_active'], unique=False)
    op.create_index(op.f('ix_prompts_is_active'), 'prompts', ['is_active'], unique=False)
    op.create_index(op.f('ix_prompts_name'), 'prompts', ['name'], unique=False)
    op.create_index('ix_prompts_name_version', 'prompts', ['name', 'version'], unique=False)
    op.create_table('suggestion_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('top_entry_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_events_action'), 'suggestion_events', ['action'], unique=False)
    op.create_index('ix_suggestion_events_action_created', 'suggestion_events', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_suggestion_events_created_at'), 'suggestion_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_suggestion_events_session_id'), 'suggestion_events', ['session_id'], unique=False)
    op.create_index('ix_suggestion_events_user_created', 'suggestion_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_suggestion_events_user_id'), 'suggestion_events', ['user_id'], unique=False)
    op.create_table('synonyms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synonyms_term'), 'synonyms', ['term'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_category'), 'tags', ['category'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('agent_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('call_type', sa.String(length=50), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_calls_call_type'), 'agent_calls', ['call_type'], unique=False)
    op.create_index(op.f('ix_agent_calls_created_at'), 'agent_calls', ['created_at'], unique=False)
    op.create_index('ix_agent_calls_session_created', 'agent_calls', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_calls_session_id'), 'agent_calls', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_calls_status'), 'agent_calls', ['status'], unique=False)
    op.create_index(op.f('ix_agent_calls_tool_name'), 'agent_calls', ['tool_name'], unique=False)
    op.create_index('ix_agent_calls_type_status', 'agent_calls', ['call_type', 'status'], unique=False)
    op.create_table('entry_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(dim=3072), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_embeddings_entry_id'), 'entry_embeddings', ['entry_id'], unique=False)
    op.create_table('entry_incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.String(length=255), nullable=False),
    sa.Column('incident_source', sa.String(length=100), nullable=False),
    sa.Column('incident_url', sa.String(length=1000), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_incidents_entry_id'), 'entry_incidents', ['entry_id'], unique=False)
    op.create_index('ix_entry_incidents_incident_id', 'entry_incidents', ['incident_id'], unique=False)
    op.create_table('entry_symptoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('symptom_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_symptoms_entry_id'), 'entry_symptoms', ['entry_id'], unique=False)
    op.create_index('ix_entry_symptoms_entry_order', 'entry_symptoms', ['entry_id', 'order_index'], unique=False)
    op.create_table('entry_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'tag_id', name='uq_entry_tag')
    )
    op.create_index(op.f('ix_entry_tags_entry_id'), 'entry_tags', ['entry_id'], unique=False)
    op.create_index('ix_entry_tags_entry_tag', 'entry_tags', ['entry_id', 'tag_id'], unique=False)
    op.create_index(op.f('ix_entry_tags_tag_id'), 'entry_tags', ['tag_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='review_status'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('rca_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_entry_id'), 'reviews', ['entry_id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_table('solutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('solution_type', sa.Enum('WORKAROUND', 'RESOLUTION', name='solution_type'), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_entry_id'), 'solutions', ['entry_id'], unique=False)
    op.create_index(op.f('ix_solutions_solution_type'), 'solutions', ['solution_type'], unique=False)
    op.create_table('agent_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_call_id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('solution_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('citation_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_call_id'], ['agent_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_suggestions_agent_call_id'), 'agent_suggestions', ['agent_call_id'], unique=False)
    op.create_index('ix_agent_suggestions_entry', 'agent_suggestions', ['entry_id'], unique=False)
    op.create_index(op.f('ix_agent_suggestions_entry_id'), 'agent_suggestions', ['entry_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_call_id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.Enum('ALLOWED', 'DENIED', 'REQUIRES_APPROVAL', name='policy_decision_result'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evaluated_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_call_id'], ['agent_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_agent_call_id'), 'policy_decisions', ['agent_call_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_created_at'), 'policy_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_policy_decisions_decision'), 'policy_decisions', ['decision'], unique=False)
    op.create_index('ix_policy_decisions_policy_decision', 'policy_decisions', ['policy_name', 'decision'], unique=False)
    op.create_index(op.f('ix_policy_decisions_policy_name'), 'policy_decisions', ['policy_name'], unique=False)
    op.create_table('review_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('LEAD', 'REVIEWER', 'OBSERVER', name='participant_role'), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_participants_review_id'), 'review_participants', ['review_id'], unique=False)
    op.create_index('ix_review_participants_review_user', 'review_participants', ['review_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_review_participants_user_id'), 'review_participants', ['user_id'], unique=False)
    op.create_table('solution_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(dim=3072), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_embeddings_solution_id'), 'solution_embeddings', ['solution_id'], unique=False)
    op.create_table('solution_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('rollback_action', sa.Text(), nullable=True),
    sa.Column('rollback_command', sa.Text(), nullable=True),
    sa.Column('step_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_steps_solution_id'), 'solution_steps', ['solution_id'], unique=False)
    op.create_index('ix_solution_steps_solution_order', 'solution_steps', ['solution_id', 'order_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_solution_steps_solution_order', table_name='solution_steps')
    op.drop_index(op.f('ix_solution_steps_solution_id'), table_name='solution_steps')
    op.drop_table('solution_steps')
    op.drop_index(op.f('ix_solution_embeddings_solution_id'), table_name='solution_embeddings')
    op.drop_table('solution_embeddings')
    op.drop_index(op.f('ix_review_participants_user_id'), table_name='review_participants')
    op.drop_index('ix_review_participants_review_user', table_name='review_participants')
    op.drop_index(op.f('ix_review_participants_review_id'), table_name='review_participants')
    op.drop_table('review_participants')
    op.drop_index(op.f('ix_policy_decisions_policy_name'), table_name='policy_decisions')
    op.drop_index('ix_policy_decisions_policy_decision', table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_decision'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_created_at'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_agent_call_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_agent_suggestions_entry_id'), table_name='agent_suggestions')
    op.drop_index('ix_agent_suggestions_entry', table_name='agent_suggestions')
    op.drop_index(op.f('ix_agent_suggestions_agent_call_id'), table_name='agent_suggestions')
    op.drop_table('agent_suggestions')
    op.drop_index(op.f('ix_solutions_solution_type'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_entry_id'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_entry_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_entry_tags_tag_id'), table_name='entry_tags')
    op.drop_index('ix_entry_tags_entry_tag', table_name='entry_tags')
    op.drop_index(op.f('ix_entry_tags_entry_id'), table_name='entry_tags')
    op.drop_table('entry_tags')
    op.drop_index('ix_entry_symptoms_entry_order', table_name='entry_symptoms')
    op.drop_index(op.f('ix_entry_symptoms_entry_id'), table_name='entry_symptoms')
    op.drop_table('entry_symptoms')
    op.drop_index('ix_entry_incidents_incident_id', table_name='entry_incidents')
    op.drop_index(op.f('ix_entry_incidents_entry_id'), table_name='entry_incidents')
    op.drop_table('entry_incidents')
    op.drop_index(op.f('ix_entry_embeddings_entry_id'), table_name='entry_embeddings')
    op.drop_table('entry_embeddings')
    op.drop_index('ix_agent_calls_type_status', table_name='agent_calls')
    op.drop_index(op.f('ix_agent_calls_tool_name'), table_name='agent_calls')
    op.drop_index(op.f('ix_agent_calls_status'), table_name='agent_calls')
    op.drop_index(op.f('ix_agent_calls_session_id'), table_name='agent_calls')
    op.drop_index('ix_agent_calls_session_created', table_name='agent_calls')
    op.drop_index(op.f('ix_agent_calls_created_at'), table_name='agent_calls')
    op.drop_index(op.f('ix_agent_calls_call_type'), table_name='agent_calls')
    op.drop_table('agent_calls')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_category'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_synonyms_term'), table_name='synonyms')
    op.drop_table('synonyms')
    op.drop_index(op.f('ix_suggestion_events_user_id'), table_name='suggestion_events')
    op.drop_index('ix_suggestion_events_user_created', table_name='suggestion_events')
    op.drop_index(op.f('ix_suggestion_events_session_id'), table_name='suggestion_events')
    op.drop_index(op.f('ix_suggestion_events_created_at'), table_name='suggestion_events')
    op.drop_index('ix_suggestion_events_action_created', table_name='suggestion_events')
    op.drop_index(op.f('ix_suggestion_events_action'), table_name='suggestion_events')
    op.drop_table('suggestion_events')
    op.drop_index('ix_prompts_name_version', table_name='prompts')
    op.drop_index(op.f('ix_prompts_name'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_is_active'), table_name='prompts')
    op.drop_index('ix_prompts_active', table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_entries_workflow_state'), table_name='entries')
    op.drop_index('ix_entries_workflow_severity', table_name='entries')
    op.drop_index(op.f('ix_entries_title'), table_name='entries')
    op.drop_index(op.f('ix_entries_status'), table_name='entries')
    op.drop_index(op.f('ix_entries_severity'), table_name='entries')
    op.drop_index(op.f('ix_entries_merged_into_id'), table_name='entries')
    op.drop_index('ix_entries_created_at', table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_user', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attachments_entity_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_id'), table_name='attachments')
    op.drop_index('ix_attachments_entity', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_incident_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_created_at'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
